blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” è³ªå•ãŒã‚ã‚‹ï¼ŸDiscussionsã§èã„ã¦ã¿ã‚ˆã†ï¼
    url: https://github.com/stylebikeweb/.github/discussions
    about: ãƒã‚°ã˜ã‚ƒãªã„è³ªå•ã¯ã“ã£ã¡ã§
  # - name: ğŸ“š ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆã‚’èª­ã‚€
  #   url: https://docs.example.com
  #   about: ä½¿ã„æ–¹ã®è©³ç´°ã¯ã“ã¡ã‚‰ã‚’ãƒã‚§ãƒƒã‚¯ï¼
